// Load environment variables from the .env file generated by 1Password
require("dotenv").config({ path: "./.env" });

console.log("🏃 App is running...");

const keys = ["DB_USER", "DB_PASSWORD"];
let allValid = true;

for (const key of keys) {
  const envVar = process.env[key];

  if (envVar === undefined) {
    console.error(`❌ Missing environment variable: ${key}`);
    allValid = false;
    continue;
  }

  if (envVar.toString().trim() === "") {
    console.error(
      `❌ Environment variable set but empty: ${key} (must have a value)`,
    );
    allValid = false;
    continue;
  }
}

if (!allValid) {
  process.exit(1);
}

console.log("🔌 Connecting to database...");
setTimeout(() => {
  // Pretend our credentials were used successfully.
  console.log(`✅ Connected to database as '${process.env.DB_USER}'.`);
  console.log("📦 Ready to perform queries.");
}, 1000);
